### ISSUE TITLE
CYSCS, dependent packages: installation issues

### ISSUE THREAD

**Issue by mdsjazz** [ajfriend/cyscs#1]
My apologies if this is a problem caused by my own system. Please send me resources so I can remedy this in case it is just my system. I'm still looking into this.

Expected: I can install NCVX, SCSPROX, and notably CYSCS without any errors

Reality: Installing NCVX, SCSPROX, and notably CYSCS is unsuccessful. It looks like the CYSCS installation cannot recognize NumPy as a module even though it is installed, and NCVX, SCSPROX, and CYSCS respectively fail to install. I receive the following error message:

`    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-install-e1u0vey2/cyscs/setup.py'"'"'; __file__='"'"'/private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-install-e1u0vey2/cyscs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-pip-egg-info-v9hxlb50
         cwd: /private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-install-e1u0vey2/cyscs/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-install-e1u0vey2/cyscs/setup.py", line 6, in <module>
        from setup_helper import glober, add_blas_lapack_info
      File "/private/var/folders/mr/pwww9_7d2vq4qsw9dp8xg9b40000gn/T/pip-install-e1u0vey2/cyscs/setup_helper.py", line 2, in <module>
        from numpy.distutils.system_info import get_info
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
I receive the same error message when pip installing NCVX, SCSPROX, and CYSCS, and I assume/read it's because the first two modules need CYSCS to be installed. It cannot install because NumPy is not recognized. When I try to install from source, I receive a different error message which appears to also take issue with CYSCS installation.

`error: Setup script exited with error: Command "x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/mikey/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/mikey/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/mikey/anaconda3/include -DPYTHON -DDLONG -DCTRLC=1 -DCOPYAMATRIX -DSCIPY_MKL_H -DHAVE_CBLAS -DLAPACK_LIB_FOUND -Ic/scs/ -Ic/scs/include -Ic/scs/linsys -I/Users/mikey/anaconda3/include -I/Users/mikey/anaconda3/lib/python3.7/site-packages/numpy/core/include -Ic/scs/linsys/direct/ -Ic/scs/linsys/direct/external/ -I/Users/mikey/anaconda3/include/python3.7m -c cyscs/_direct.c -o build/temp.macosx-10.9-x86_64-3.7/cyscs/_direct.o -O3" failed with exit status 1
`

I wonder if this is an issue with my own system, or if the install file simply did not import NumPy, and if this is a fix I can swoop in and fix or if I can't find the correct install file 

One notable thing here is that I wonder if I did not set up my dependencies correctly. My NumPy was installed through Conda, while I am trying to install all of this with pip. I've messed up enough environments and installed/uninstalled enough packages on my computer to expect I've broken things I don't understand. I wish not to uninstall/reinstall NumPy before I know that it's safe for all of my other Python packages, and I don't want to install another NumPy with pip.

Is this anything that can be helped? My apologies once again if I'm being dense, and thank you so much in advance.

**Comment by mdsjazz** [comment]
I installed SCS, and it looks like it installed NumPy for me—that issue was solved. Now I've got 100+ more. Here is my output error log.
[CYSCS Installation Error Log - 2020-9-2 -- 22-51GMT.txt](https://github.com/ajfriend/cyscs/files/5159167/CYSCS.Installation.Error.Log.-.2020-9-2.--.22-51GMT.txt)

**Comment by rodfloripa** [comment]
I have the same problem

**Comment by makansij** [comment]
Has there been any resolution/progress on this issue?  I have the same problem.

**EDIT**:  It very clearly says "DO NOT INSTALL FROM PIP" here: https://github.com/cvxgrp/ncvx.

**Comment by bodono** [comment]
I'm not sure if this repo is still maintained. Is there some reason not to use the main [SCS python interface](https://github.com/bodono/scs-python)?

**Comment by nicklar** [comment]
I have the same problem. Trying to install ncvx which depends on this but I can't get this to install. Any ideas?
